WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
VIRTUAL_WIDTH = 256
VIRTUAL_HEIGHT = 144
TILE_SIZE = 16
SCREEN_TILE_WIDTH = VIRTUAL_WIDTH / TILE_SIZE
SCREEN_TILE_HEIGHT = VIRTUAL_HEIGHT / TILE_SIZE
CAMERA_SPEED = 100
BACKGROUND_SCROLL_SPEED = 10
TILE_SET_WIDTH = 5
TILE_SET_HEIGHT = 4
TILE_SETS_WIDE = 6
TILE_SETS_TALL = 10
TOPPER_SETS_WIDE = 6
PIPE_WIDTH = 32
PIPE_HEIGHT = 48
TOPPER_SETS_TALL = 18
TOPPER_SETS = TOPPER_SETS_WIDE * TOPPER_SETS_TALL
TILE_SETS = TILE_SETS_WIDE * TILE_SETS_TALL
PLAYER_WALK_SPEED = 60
PLAYER_JUMP_VELOCITY = -300
SNAIL_MOVE_SPEED = 16
TILE_ID_EMPTY = 5
TILE_ID_UNDERGROUND_GROUND = 6
TILE_ID_UNDERGROUND_CEILING = 7
UNDERGROUND_LEVEL_START = 11
TILE_ID_GROUND = 3
COLLIDABLE_TILES = {
    TILE_ID_GROUND,
    TILE_ID_UNDERGROUND_GROUND,
    TILE_ID_UNDERGROUND_CEILING
}
BUSH_IDS = {
    1, 2, 5, 6, 7
}
COIN_IDS = {
    1, 2, 3
}
CRATES = {
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12
}
GEMS = {
    1, 2, 3, 4, 5, 6, 7, 8
}
JUMP_BLOCKS = {}
for i = 1, 30 do
    table.insert(JUMP_BLOCKS, i)
end