WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
VIRTUAL_WIDTH = 256
VIRTUAL_HEIGHT = 144
TILE_SIZE = 16
SCREEN_TILE_WIDTH = VIRTUAL_WIDTH / TILE_SIZE
SCREEN_TILE_HEIGHT = VIRTUAL_HEIGHT / TILE_SIZE
CAMERA_SPEED = 100
BACKGROUND_SCROLL_SPEED = 10
TILE_SET_WIDTH = 5
TILE_SET_HEIGHT = 4
TILE_SETS_WIDE = 6
TILE_SETS_TALL = 10
TOPPER_SETS_WIDE = 6
PIPE_WIDTH = 32
PIPE_HEIGHT = 48
TOPPER_SETS_TALL = 18
TOPPER_SETS = TOPPER_SETS_WIDE * TOPPER_SETS_TALL
TILE_SETS = TILE_SETS_WIDE * TILE_SETS_TALL
PLAYER_WALK_SPEED = 60
PLAYER_JUMP_VELOCITY = -300
SNAIL_MOVE_SPEED = 16

PLAYER_STATE_SMALL = 1
PLAYER_STATE_BIG = 2
PLAYER_STATE_FIRE = 3

POWERUP_SIZE_ID = 1
POWERUP_FIRE_ID = 2

TILE_ID_EMPTY = 5
TILE_ID_UNDERGROUND_GROUND = 6
TILE_ID_UNDERGROUND_CEILING = 7
TILE_ID_CASTLE_GROUND = 8
UNDERGROUND_LEVEL_START = 11
TILE_ID_GROUND = 3
TILE_ID_LAVA = 9       -- Lava body tile
TILE_ID_LAVA_TOP = 10  -- Lava surface / topper tile
TILE_ID_CASTLE_BRICK = 11 -- Castle ceiling/wall brick (used in level 26)

COLLIDABLE_TILES = {
    TILE_ID_GROUND,
    TILE_ID_UNDERGROUND_GROUND,
    TILE_ID_UNDERGROUND_CEILING,
    TILE_ID_CASTLE_GROUND
}
BUSH_IDS = {
    1, 2, 5, 6, 7
}
COIN_IDS = {
    1, 2, 3
}

FIREBALL_SPEED = 100
FIREBALL_WIDTH = 8
FIREBALL_HEIGHT = 8
CRATES = {
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12
}
GEMS = {
    1, 2, 3, 4, 5, 6, 7, 8
}
JUMP_BLOCKS = {}
for i = 1, 30 do
    table.insert(JUMP_BLOCKS, i)
end